### ISSUE TITLE
Crashes with Terraria 1.3

### ISSUE THREAD

**Issue by 999eagle** [atom0s/Detox#13]
I'm trying to use Detox with Terraria 1.3, but everytime I start it, it just crashes without any error message. The log indicates that the constructor for Terraria.Main itself throws a System.MissingMethodException because the method "Void Newtonsoft.Json.JsonSerializerSettings.set_MetadataPropertyHandling(Newtonsoft.Json.MetadataPropertyHandling)" can't be found.

**Comment by 999eagle** [comment]
I've found the source of the issue, but have no idea, why this happens:
```
//Terraria.Main.cctor()
static Main()
{
	...
	Main.Configuration = new Preferences(Main.SavePath + Path.DirectorySeparatorChar + "config.json", false, false);
	...
}

//Terraria.IO.Preferences.ctor()
public Preferences(string path, bool parseAllTypes = false, bool useBson = false)
{
	this._path = path;
	this.UseBson = useBson;
	if (parseAllTypes)
	{
		JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings();
		jsonSerializerSettings.set_TypeNameHandling(4);
		jsonSerializerSettings.set_MetadataPropertyHandling(1);
		this._serializerSettings = jsonSerializerSettings;
		return;
	}
	this._serializerSettings = new JsonSerializerSettings();
}
```

Although parseAllTypes should be false in this call it seems to still fail in this method. In Main.cctor() are also no other calls to this Preferences.ctor() and the stack trace ends with
System.Reflection.TargetInvocationException ---> System.TypeInitializationException ---> System.MissingMethodException: Method not found: "Void Newtonsoft.Json.JsonSerializerSettings.set_MetadataPropertyHandling(Newtonsoft.Json.MetadataPropertyHandling)".
   at Terraria.IO.Preferences..ctor(String path, Boolean parseAllTypes, Boolean useBson)
   at Terraria.Main..cctor()

**Comment by atom0s** [comment]
Detox is not updated for Terraria 1.3.0.x and won't be free if I do update it.
